### ISSUE TITLE
Config: token items to "creds" dict

### ISSUE THREAD

**Issue by RememberTheAir** [zeroone2numeral2/reddit-test#79]
```toml
[creds.telegram]
token = ""

[creds.imgur]
token = ""

[creds.reddit]
token = ""
```
